### ISSUE TITLE
First time user- not working

### ISSUE THREAD

**Issue by tibitoy** [imilne/tablet#16]
I downloaded tablet via bioconda but when I try to activate it I keep getting this:

Exception in thread "main" java.lang.ExceptionInInitializerError
Caused by: java.awt.HeadlessException: 
No X11 DISPLAY variable was set, but this program performed an operation which requires it.
	at sun.awt.HeadlessToolkit.getMenuShortcutKeyMask(HeadlessToolkit.java:236)
	at tablet.gui.Tablet.<clinit>(Tablet.java:35)

Not sure what I'm doing wrong but any help would be much appreciated!

**Comment by peterjc** [comment]
Are you on Linux (which version)? Do you have an X Windows system?

**Comment by peterjc** [comment]
Closing as no reply
